apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oauth2-proxy-jaeger
spec:
  dnsNames:
    - jaeger.login.outi.ir
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: jaeger-tls
