apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ory-selfservice-rust
spec:
  secretName: ory-selfservice-rust-tls
  dnsNames:
    - "identity.outi.ir"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
