log:
  level: debug
  format: text

serve:
  proxy:
    port: 4455
    host: 0.0.0.0
  api:
    port: 4456
    host: 0.0.0.0

access_rules:
  repositories:
    - file:///etc/config/oathkeeper/rules.json

authenticators:
  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      preserve_path: true
      subject_from: identity.id
      extra_from: "@this"

authorizers:
  allow:
    enabled: true

mutators:
  header:
    enabled: true
    config:
      headers:
        x-user-id: "{{ print .Subject }}"
        x-user-email: "{{ print .Extra.identity.traits.email }}"

errors:
  fallback:
    - redirect
    - json
  handlers:
    redirect:
      enabled: true
      config:
        to: http://localhost:3000/auth/login
        return_to_query_param: return_to
        code: 302
        when:
          - error:
              - unauthorized
              - forbidden
            request:
              header:
                accept:
                  - text/html
    json:
      config: {}
