apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kratos-auth
spec:
  secretName: kratos-auth-tls
  dnsNames:
    - "web.login.outi.ir"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer

