apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos-auth
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: kratos-auth
  template:
    metadata:
      labels:
        app: kratos-auth
    spec:
      imagePullSecrets:
        - name: ghcr-credentials
      containers:
        - name: kratos-auth
          image: ghcr.io/distributed-timetable-assistant/kratos-auth:latest
          imagePullPolicy: Always
          env:
            - name: NEXT_PUBLIC_ORY_SDK_URL
              value: https://web.login.outi.ir/
            - name: PUBLIC_BASE_URL
              value: https://web.login.outi.ir
            - name: KRATOS_PUBLIC_URL
              value: http://kratos-public:4433
            - name: HYDRA_ADMIN_URL
              value: http://hydra-admin:4445
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: public-assets
              mountPath: /app/public
              readOnly: true
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 0m
              memory: 0Mi
      volumes:
        - name: public-assets
          configMap:
            name: kratos-auth-public-assets
