apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iam
nameSuffix: -svc2

resources:
  - ../../base
  - certificate.yml

patches:
  - path: deployment-patch.yml
  - path: service-patch.yml
