apiVersion: apps/v1
kind: Deployment
metadata:
  name: ory-selfservice
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: ory-selfservice
  template:
    metadata:
      labels:
        app: ory-selfservice
    spec:
      containers:
        - name: ory-selfservice
          image: backendd/dita.ory-selfservice-rust:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ORY_UI__LISTEN_ADDR
              value: "0.0.0.0:8080"
            - name: ORY_UI__PUBLIC_BASE_URL
              value: "https://web.login.outi.ir"
            - name: ORY_UI__KRATOS_PUBLIC_URL
              value: "http://kratos-public:4433"
            - name: ORY_UI__HYDRA_ADMIN_URL
              value: "http://hydra-admin:4445"
            - name: RUST_LOG
              value: debug
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 0m
              memory: 0Mi