apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-svc2
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy-svc2:4180/oauth2/svc2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://svc2.login.outi.ir/oauth2/svc2/start?rd=$scheme://$host$request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email,Authorization
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - svc2.login.outi.ir
      secretName: svc2-tls
  rules:
    - host: svc2.login.outi.ir
      http:
        paths:
          - path: /svc2
            pathType: Prefix
            backend:
              service:
                name: whoami-svc2
                port:
                  name: http
