apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra
data:
  hydra.yml: |
    log:
      level: debug
      format: text

    serve:
      public:
        host: 0.0.0.0
        port: 4444
      admin:
        host: 0.0.0.0
        port: 4445
      cookies:
        secure: false
        same_site_mode: Lax

    urls:
      self:
        issuer: https://auth.outi.ir
      login: https://web.login.outi.ir/oauth2/login
      consent: https://web.login.outi.ir/oauth2/consent
      logout: https://web.login.outi.ir/logout
