apiVersion: v1
kind: ConfigMap
metadata:
  name: hydra
data:
  hydra.yml: |
    log:
      level: debug
      format: text

    serve:
      public:
        host: 0.0.0.0
        port: 4444
      admin:
        host: 0.0.0.0
        port: 4445
      cookies:
        secure: false
        same_site_mode: Lax

    urls:
      self:
        issuer: https://hydra.st.dita.hasankarimi.ir
      login: https://iam.st.dita.hasankarimi.ir/hydra/login
      consent: https://iam.st.dita.hasankarimi.ir/hydra/consent
      logout: https://iam.st.dita.hasankarimi.ir/hydra/logout
