apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos
data:
  identity.schema.json: |
    {
      "$id": "https://schemas.ory.sh/presets/kratos/identity.email.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Person",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail",
              "minLength": 3
            },
            "name": {
              "type": "object",
              "properties": {
                "first": { "type": "string" },
                "last": { "type": "string" }
              }
            }
          },
          "required": ["email"],
          "additionalProperties": false
        }
      }
    }
  kratos.yml: |
    version: v0.13.0

    serve:
      public:
        base_url: https://web.login.outi.ir/kratos/
        cors:
          enabled: true
          allow_credentials: true
          allowed_origins:
            - https://web.login.outi.ir
          allowed_methods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
          allowed_headers:
            - Content-type
            - Authorization
      admin:
        base_url: http://kratos-admin:4434/

    session:
      cookie:
        domain: .outi.ir

    selfservice:
      default_browser_return_url: https://web.login.outi.ir/
      allowed_return_urls:
        - https://web.login.outi.ir
        - https://web.login.outi.ir/
        - https://web.login.outi.ir/hydra/login
        - https://web.login.outi.ir/hydra/consent
        - https://web.login.outi.ir/hydra/logout
        - https://login.outi.ir
        - https://login.outi.ir/
        - https://login.outi.ir/svc1
        - https://login.outi.ir/svc2

      methods:
        password:
          enabled: true
        totp:
          config:
            issuer: Kratos
          enabled: true
        lookup_secret:
          enabled: true
        link:
          enabled: true
        code:
          enabled: true

      flows:
        error:
          ui_url: https://web.login.outi.ir/auth/error

        settings:
          ui_url: https://web.login.outi.ir/auth/settings
          privileged_session_max_age: 15m
          required_aal: highest_available

        recovery:
          enabled: true
          ui_url: https://web.login.outi.ir/auth/recovery
          use: code

        verification:
          enabled: true
          ui_url: https://web.login.outi.ir/auth/verification
          use: code
          after:
            default_browser_return_url: https://web.login.outi.ir/

        logout:
          after:
            default_browser_return_url: https://web.login.outi.ir/auth/login

        login:
          ui_url: https://web.login.outi.ir/auth/login
          lifespan: 10m

        registration:
          lifespan: 10m
          ui_url: https://web.login.outi.ir/auth/registration
          after:
            password:
              hooks:
                - hook: session
                - hook: show_verification_ui

    log:
      level: debug
      format: text
      leak_sensitive_values: true

    ciphers:
      algorithm: xchacha20-poly1305

    hashers:
      algorithm: bcrypt
      bcrypt:
        cost: 8

    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/kratos/identity.schema.json

    courier:
      smtp:
        connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

    feature_flags:
      use_continue_with_transitions: true
